### ISSUE TITLE
Can't verify integrity of latest patch

### ISSUE THREAD

**Issue by Esokrates** [kdave/grsecurity-patches#2]
gpgv2 --keyring=./keyring.gpg grsecurity-3.1-4.9.24-201704252333.patch.sig spender-gpg-key.asc 
gpgv: Signature made Wed 26 Apr 2017 05:36:10 AM CEST
gpgv:                using RSA key 44D1C0F82525FE49
gpgv: BAD signature from "Bradley Spengler (spender) <spender@grsecurity.net>"

**Comment by kdave** [comment]
Works for me.

**Comment by Esokrates** [comment]
Yeah, I have made a stupid mistake, hence I closed it, as the mistake I made is embarrassingly obvious.
Sorry for the noise!
